### ISSUE TITLE
Extend support to user-owned containers

### ISSUE THREAD

**Issue by vlaurin** [vlaurin/action-ghcr-prune#2]
Using endpoints dedicated to authenticated user packages:
- https://octokit.github.io/rest.js/v18#packages-get-all-package-versions-for-a-package-owned-by-the-authenticated-user
- https://octokit.github.io/rest.js/v18#packages-delete-package-version-for-authenticated-user

**Comment by mpfeil** [comment]
Hi @vlaurin,

thank your for this repository and action. I am already using it in one of our organizations.
I would love to contribute and work on this feature.

Are you already working on it? Or can I pick it up?

**Comment by vlaurin** [comment]
@mpfeil thank you for volunteering, it's all yours I haven't started anything on this one.

I would just advise you wait for #5 to land (should be today) as I've started refactoring the structure in it to add unit testing with Jest and I wouldn't want that to conflict with your work.
