### ISSUE TITLE
Fails to delete images with HTTP error

### ISSUE THREAD

**Issue by FlippievanDyk** [vlaurin/action-ghcr-prune#27]
This was working perfectly, but now it is failing with the stack trace below. 

I am not convinced it is necessarily the action, I also get errors when deleting manually, just posting this here for **IF** it does turnout to be the action.

If this is GitHub side, please close the issue, just bringing it to your attention.

I've only edited out the organization and repo names.

__________

Run vlaurin/action-ghcr-prune@main
  with:
    token: ***
    organization: ORG
    container: package
    dry-run: false
    tag-regex: package-v[a-fA-F0-9]+[.][a-fA-F0-9]+[.][a-fA-F0-9]+develop[a-fA-F0-9]+
    keep-tags: latest
  stable
  
    older-than: 0
    keep-last: 0
    untagged: false
Crawling through all versions to build pruning list...
Found 4 versions to prune out of 12 on page 1
Found a total of 4 versions to prune
Pruning 4 versions...
Pruning version #19858792 named 'sha256:a90f832e06654a1626a96d6b21be6c148ed43b9a2d9a189352a027f7a72c[38](https://github.com/ORG/repo/runs/6224597191?check_suite_focus=true#step:2:38)81'...
Failed to prune because of:  RequestError [HttpError]: Server Error
    at /home/runner/work/_actions/vlaurin/action-ghcr-prune/main/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Pruned 0 versions
    at async /home/runner/work/_actions/vlaurin/action-ghcr-prune/main/src/pruning.js:[39](https://github.com/ORG/repo/runs/6224597191?check_suite_focus=true#step:2:39):7
Error: Failed to prune some versions: 0 out of 4 versions were pruned
    at async run (/home/runner/work/_actions/vlaurin/action-ghcr-prune/main/index.js:60:24) {
  status: [50](https://github.com/ORG/repo/runs/6224597191?check_suite_focus=true#step:2:50)2,
  response: {
    url: 'https://api.github.com/orgs/org/packages/container/package/versions/198[58](https://github.com/ORG/repo/runs/6224597191?check_suite_focus=true#step:2:58)792',
    status: 502,
    headers: {
      connection: 'close',
      'content-length': '32',
      'content-type': 'application/json',
      date: 'Fri, 29 Apr 2022 07:[59](https://github.com/ORG/repo/runs/6224597191?check_suite_focus=true#step:2:59):05 GMT',
      etag: '"[62](https://github.com/ORG/repo/runs/6224597191?check_suite_focus=true#step:2:62)6b994b-20"',
      server: 'GitHub.com',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-github-request-id': '0502:7C22:6CDF50:71EF89:626B9ABE'
    },
    data: { message: 'Server Error' }
  },
  request: {
    method: 'DELETE',
    url: 'https://api.github.com/orgs/org/packages/container/package/versions/19858792',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.5.1 Node.js/16.13.0 (linux; x[64](https://github.com/ORG/repo/runs/6224597191?check_suite_focus=true#step:2:64))',
      authorization: 'token [REDACTED]',
      'content-length': 0
    },
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}

**Comment by vlaurin** [comment]
@FlippievanDyk thank you for flagging this up. Is this consistently failing? if you rerun the workflow now is it still failing with the same error?

**Comment by FlippievanDyk** [comment]
It does fail consistently. It is not run everyday, so I ignored it the first time it happened, hoping it was a temporary issue on githubs end. 

If there is nothing to delete it passes. 
If there is a package to delete, it fails on the attempt. 

I re-ran, and it failed with the same error. Unfortunately, I deleted the packages manually the re-ran again, just so my status checks do not reflect the fail. (They are not really relevant to the release, only to housekeeping)... 
I don't know if it deleted, but failed to get a correct response? The more I think about it, I suspect the issue is really with GitHub's Api, and not this action. Do you know where I should report that?

**Comment by vlaurin** [comment]
To be safe I just ran the action against one of my repos, using a similar configuration to your action, and it pruned okay. So the way the action is calling the GitHub API doesn't seem to be at fault. That combined with the response code 502 would indeed makes me lean towards an issue on the GitHub's side.

As far as reporting an issue, you can contact GitHub's support here: https://support.github.com/request

Out of curiosity, how many pages of versions do you have for the package you are trying to delete? I found that thread from last year which describes something not too dissimilar: https://github.community/t/the-github-packages-service-encountered-an-error/18057/26

**Comment by vlaurin** [comment]
I'll keep the issue open for now. If you don't mind sharing the cause once you've got it, it could help others :)
