### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by oerp-odoo** [vlaurin/action-ghcr-prune#66]
Would be good to update action, so warning would not appear anymore: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by vlaurin** [comment]
Yep, this has already been done on `main` as part of #45 but hasn't been released yet.
This will be part of the next minor release, 0.5.0, I should be able to release it in the coming days.

**Comment by oerp-odoo** [comment]
Thanks!

**Comment by vlaurin** [comment]
[Version 0.5.0](https://github.com/vlaurin/action-ghcr-prune/releases/tag/v0.5.0) has now been released.
