### ISSUE TITLE
Invalid version number specified in README.md

### ISSUE THREAD

**Issue by timofey-drozhzhin** [vlaurin/action-ghcr-prune#68]
The version number `v0.5` provided in README.md is not working. It produces the following error:
```
Unable to resolve action `vlaurin/action-ghcr-prune@v0.5`, unable to find version `v0.5`
```

Either the README.md needs say `v0.5.0` or image tagged with v0.5.

Thanks :)

**Comment by vlaurin** [comment]
Sorry for that, I've fixed the README
