### ISSUE TITLE
Found a total of 0 versions to prune

### ISSUE THREAD

**Issue by cenobitedk** [vlaurin/action-ghcr-prune#7]
Hi

I'm trying to set this up, but for some reason it seem to find 0 candidates to delete despite finding many versions. What am I doing wrong?

This is my config and the result:
```
Run vlaurin/action-ghcr-prune@main
  with:
    token: ***
    container: my-package-name
    dry-run: true
    older-than: 14
    keep-last: 10
    untagged: false

Crawling through all versions to build pruning list...
Found 0 versions to prune out of 100 on page 1
Found 0 versions to prune out of 100 on page 2
Found 0 versions to prune out of 19 on page 3
Keeping the last 10 versions, sorted by creation date
Found a total of 0 versions to prune
Pruning 0 versions...
Pruned 0 versions
```

**Comment by vlaurin** [comment]
@cenobitedk You either need `untagged` to be set to `true` if your are looking to prune untagged versions; or you need a `tag-regex` to be defined if you are looking to prune tagged versions. Or you can enable both, depends on what you are trying to prune.

By defaults both are disabled which means no versions will match, which is exactly what's happening in your scenario. The `older-than` and `keep-last` parameters only apply on top of versions selected by `untagged` and/or `tag-regex` inputs.

**Comment by cenobitedk** [comment]
@vlaurin  Ah ok, thank you for clarifying! 🙏

**Comment by vlaurin** [comment]
No worries, hope it works okay for you now.

**Comment by cenobitedk** [comment]
It does 👍
