### ISSUE TITLE
update Node.js version to 20

### ISSUE THREAD

**Issue by mooxl** [vlaurin/action-ghcr-prune#77]
Hey there,
Firstly, just want to say a big thank you for developing ﻿this action. It's been a huge help for my projects!

I've recently bumped into a small hiccup: GitHub has decided to deprecate Node.js 16, pushing us towards Node.js 20. Because of this, I've been seeing a warning in my pipelines because of this action.

It'd be amazing if you could find some time to update the Node.js version:)

Cheers,
Max

**Comment by vlaurin** [comment]
@mooxl Thank you for the nudge, I've released 0.6.0 with the upgrade to Node 20.
